[package]
name = "jorsan/ink-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
goodsignal = "stravant/goodsignal@0.3.0"
maid = "coiorevent8/maid@3.4.0"